### ISSUE TITLE
Multiple Bots

### ISSUE THREAD

**Issue by dehghanimehrdad** [php-telegram-bot/laravel#4]
Hello, I have been using the package for some time, and now I want to add more bots, like  I want to create new controller for another bot which will have its own commands and stuff, any idea?

**Comment by rafuck** [comment]
> You can easily check the bot ID and set a different config accordingly 👍

Is it possible to use different bots in different console commands? 
1) There are some tables in DB, and in these tables bot_id or something like this is not present. It is not problem?
2) And I newbie in laravel. How I can provide different config in different console commands?
