### ISSUE TITLE
install for Laravel 9

### ISSUE THREAD

**Issue by decole** [php-telegram-bot/laravel#43]
`composer require php-telegram-bot/laravel `

Print Errors:

```
Problem 1
    - Root composer.json requires php-telegram-bot/laravel ^0.0.1 -> satisfiable by php-telegram-bot/laravel[0.0.1].
    - php-telegram-bot/laravel 0.0.1 requires illuminate/database 5.* -> found illuminate/database[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
```
This repo may be install on new version Laravel 9 ?

**Comment by tyonly** [comment]
my error:
`  Problem 1
    - php-telegram-bot/laravel[1.1.0, ..., 1.1.1] require illuminate/database ^6.0 -> found illuminate/database[v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires php-telegram-bot/laravel ^1.1 -> satisfiable by php-telegram-bot/laravel[1.1.0, 1.1.1].`

**Comment by tyonly** [comment]
i have done it .i download the package,then edit the composer.json -> repositories, point to the packapge path, then call "composer require php-telegram-bot/laravel", success install the package

**Comment by decole** [comment]
my bug is being, then I migrate laravel 8 to laravel 9, i fix it delete in composer composer.lock and upping stab version on installed packages

php8.0, but php8.1 - have errors to installing this package

**Comment by noplanman** [comment]
I suggest you look into https://git.tii.tools/tii/laravel-telegram-bot
