### ISSUE TITLE
When the package will be updated for Laravel 9

### ISSUE THREAD

**Issue by Odilbukh** [php-telegram-bot/laravel#44]
When the packege will be updated for Laravel 9 and php 8.1 ?
Or how to install the package in Laravel 9 now ?

**Comment by noplanman** [comment]
I suggest you look into https://git.tii.tools/tii/laravel-telegram-bot

**Comment by Odilbukh** [comment]
> I suggest you look into https://git.tii.tools/tii/laravel-telegram-bot

@noplanman Thanks!  Yes it's usefull! But how can I find documentation of that package?

**Comment by TiiFuchs** [comment]
the linked package is now part of this library as of v2.0
