### ISSUE TITLE
Error on instalation

### ISSUE THREAD

**Issue by Odilbukh** [php-telegram-bot/laravel#45]
I have created new Laravel 8 project. Nothing changed. Laravel is fresh. And run command: 
`composer require php-telegram-bot/laravel`
it returns error like this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php-telegram-bot/laravel ^0.0.1 -> satisfiable by php-telegram-bot/laravel[0.0.1].
    - php-telegram-bot/laravel 0.0.1 requires illuminate/database 5.* -> found illuminate/database[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - symfony/deprecation-contracts v3.1.1 requires php >=8.1 -> your php version (8.0.20) does not satisfy that requirement.
    - fakerphp/faker v1.19.0 requires symfony/deprecation-contracts ^2.2 || ^3.0 -> satisfiable by symfony/deprecation-contracts[v3.1.1].
    - fakerphp/faker is locked to version v1.19.0 and an update of this package was not requested.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require php-telegram-bot/laravel:*" to figure out if any version is installable, or "composer require php-telegram-bot/laravel:^2.1" if you know which you need.

**Comment by noplanman** [comment]
I suggest you look into https://git.tii.tools/tii/laravel-telegram-bot
Hopefully soon that will become the default and moved here.

**Comment by LucaColombi** [comment]
try composer require php-telegram-bot/laravel:*
it look for a version suitable with your composer situation

**Comment by TiiFuchs** [comment]
Closed due to new code base with v2.0
