### ISSUE TITLE
Is there a way to receive generic messages?

### ISSUE THREAD

**Issue by LucaColombi** [php-telegram-bot/laravel#46]
I successful handled commands but I cannot receive generic message (like "hello!")

would need to receive them too

is it possible?

**Comment by noplanman** [comment]
Absolutely! Take a look at the [`GenericmessageCommand`](https://github.com/php-telegram-bot/example-bot/blob/e941817298dc907b8c50eee85a8c9ac00a345b8a/Commands/Message/GenericmessageCommand.php#L49).

Also, for questions like this, the support group on Telegram is quicker to get a reply :+1: :
https://t.me/PHP_Telegram_Bot_Support
