### ISSUE TITLE
Composer.org only has 2.0.3, incompatible with Laravel 10

### ISSUE THREAD

**Issue by daniel-lucio** [php-telegram-bot/laravel#55]
Laravel 10 requires illuminate/support 10

composer.org has only published  version 2.0.3
https://packagist.org/packages/php-telegram-bot/laravel#v2.0.3
in which it only supports illuminate/support 7,8,9

which makes a conflict when installing. Can you publish 2.0.4 with illuminate/support 10 included?

**Comment by TiiFuchs** [comment]
composer.org doesn't publish anything.

We're currently waiting on the release of the new php-telegram-bot version so we can publish the already updated laravel package.

Until then you can use dev-main or wait for the new release.

**Comment by daniel-lucio** [comment]
I cant use -dev because
https://packagist.org/packages/longman/telegram-bot#dev-develop
requires php 8.0, it is the same issue
